'use strict';  

var API_KEY = 'AIzaSyDsjIwrvc61c2Ckm6rHPSBNRoRBim_yw44';
var CALENDAR_ID_PRIMARY = 'eugostodequeijadinhadequeijo@gmail.com';
var CALENDAR_ID_WORK = '832fm0rrd8pr869c4e7vnhlh8c@group.calendar.google.com';

var LOCALE_SYDNEY = {
  timezone: 'Australia/Sydney',
  offset: '-13:00'
};
var LOCALE_SAOPAULO = {
  timezone: 'America/Sao_Paulo',
  offset: '-03:00'
};

var createEventGoogleCalendar = (shift, locale) => {
  return {
    'summary': shift.role,
    'location': 'Hurricane\'s Grill Circular Quay, Level 2 Gateway Sydney, Alfred St, Sydney NSW 2000, Australia',
    'description': shift.role + ' shift.\n\nAutomatically generated by Chrome Extension.',
    'start': {
      'dateTime': "2019-"+shift.date.month+"-"+correctDayWithOffset(shift.date.day,LOCALE_SYDNEY.offset)+"T"+shift.time.start+":00"+locale.offset,
      'timeZone': locale.timezone
    },
    'end': {
      'dateTime': "2019-"+shift.date.month+"-"+correctDayWithOffset(shift.date.day,LOCALE_SYDNEY.offset)+"T"+shift.time.end+":00"+locale.offset,
      'timeZone': locale.timezone
    },
    'reminders': {
      'useDefault': false,
      'overrides': [
        {'method': 'popup', 'minutes': 60}
      ]
    }
  };
};

var correctDayWithOffset = (day, offset) => {
  //FIXME problem with 1st of the month
  return parseInt(offset.split(":")[0])<-12 ? day - 1 : day;
};

var roster = {};

var loadRoster = roster => {

  $('#placeholder').hide();
  
  var shifts = $('#shifts');

  $.each(roster, function(i,shift){
    var shiftCard = '<div column><div class="ui card"><div class="content"><i class="right floated big address book icon"></i><div class="header">' +
                    shift.role +
                    '</div></div><div class="content"><h4 class="ui sub header">' +
                    shift.date.text +
                    '</h4><div class="ui small feed"><div class="event"><div class="content"><div class="summary"><p>From ' +
                    shift.time.start +
                    '</p></div></div></div><div class="event"><div class="content"><div class="summary"><p>To ' +
                    shift.time.end +
                    '</p></div></div></div></div></div><div class="extra content"><button id="shift' +
                    i + 
                    '" class="ui button">Add Google Calendar</button></div></div></div>';
        
    shifts.append(shiftCard).trigger('create');
  });

};


$(function() {
  
  $('#shifts').on("click",":button",function() {
    var btnId = $(this)[0].id;

    if(!btnId) {
      console.error("Error: didn't find the button id");
      return;
    }

    var shiftIndex = btnId.replace("shift","");

    var endpoint = 'https://www.googleapis.com/calendar/v3/calendars/' + encodeURIComponent(CALENDAR_ID_WORK) + '/events/?key=' + API_KEY;
    
    chrome.identity.getAuthToken({interactive: true}, function(token) {
      $.ajax({
          type: "POST",
          url: endpoint,
          dataType: 'json',
          async: true,
          headers: {
            'Authorization':  'Bearer ' + token,
            'Content-Type': 'application/json'
          },
          data: JSON.stringify(createEventGoogleCalendar(roster[shiftIndex],LOCALE_SYDNEY)),
          success: function (data){
            console.log(data);
          },
          error: function(err){
            console.log(err);
          }
      });
    });
  });
});


// Listener to receive the roster from background script
chrome.runtime.onMessage.addListener(
  function(request, sender, sendResponse) {
    roster = {};
    $('#shifts').empty();
    if( request.roster ) {
      roster = request.roster;
      console.log('Received from background:')
      console.log(roster);
      loadRoster(roster);
    };
  }
);